routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=>'main', 'middleware'=>['auth']], function () {
    Route::get('user/profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('profile.show');
    Route::put('user/profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('profile.update');

    Route::get('service/{id}/print', [App\Http\Controllers\ServiceController::class, 'print'])->name('service.print');
    Route::get('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupIndex'])->name('service.pickup.index');
    Route::post('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupStore'])->name('service.pickup.store');

    Route::get('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderIndex'])->name('spare_part.order.index');
    Route::post('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderStore'])->name('spare_part.order.store');

    Route::get('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedIndex'])->name('spare_part.received.index');
    Route::post('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedStore'])->name('spare_part.received.store');

    Route::get('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingIndex'])->name('spare_part.fixing.index')->middleware('role:technician');
    Route::post('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingStore'])->name('spare_part.fixing.store')->middleware('role:technician');


    Route::resource('user', App\Http\Controllers\UserController::class)->middleware('role:owner');
    Route::resource('service', App\Http\Controllers\ServiceController::class)->middleware('role:admin');
    Route::resource('customer', App\Http\Controllers\CustomerController::class)->middleware('role:admin');
    Route::resource('symptom', App\Http\Controllers\SymptomController::class)->middleware('role:admin|technician');
    Route::resource('report', App\Http\Controllers\ReportController::class)->middleware('role:admin|owner');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    protected $appends = ['display_role'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getDisplayRoleAttribute()
    {
        $result = '';
        $role = $this->attributes['role'];

        switch ($role) {
            case 'admin':
                $result = 'Admin';
                break;
            case 'technician':
                $result = 'Teknisi';
                break;
            case 'owner':
                $result = 'Owner';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Yajra\Datatables\Datatables;
use App\Models\User;
use Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $users = User::query();

            if ($request->get('role') != null) {
                if ($request->role != 'all') {
                    $users->whereRole($request->role);
                }
            }

            $users = $users->select('users.*');
            
            return Datatables::of($users)
                ->addIndexColumn()
                ->addColumn('action', function($user){
                    return view('partials._action', [
                        'model'           => $user,
                        'form_url'        => route('user.destroy', $user->id),
                        'edit_url'        => route('user.edit', $user->id)
                    ]);
                })             
                ->escapeColumns([])
                ->make(true);
        }

        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|string|max:255',
          'email' => 'required|string|email|max:255|unique:users',
          'identity_number' => 'required|numeric',
          'phone' => 'required|string|max:16',
          'password' => 'required|string|min:6|confirmed',
          'role' => 'required|string',
        ]);
        
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->identity_number = $request->identity_number;
        $user->phone = $request->phone;
        $user->role = $request->role;
        $user->password =  Hash::make($request->password);

        if ($request->hasFile('avatar')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('avatar');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'avatars';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);
           
            $user->avatar = $filename;
        }

        $user->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Akun dengan nama $user->name berhasil dibuat"
        ]);
        
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('users.edit')->with(compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'name' => 'required|string|max:255',
          'email' => 'required|unique:users,email,' . $id,
          'identity_number' => 'required|numeric',
          'phone' => 'required|string|max:16',
          'role' => 'required|string',
        ]);
        
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->identity_number = $request->identity_number;
        $user->phone = $request->phone;
        $user->role = $request->role;

        if ($request->hasFile('avatar')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('avatar');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'avatars';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);
            // hapus image lama, jika ada
            if ($user->avatar) {
                $old_image = $user->avatar;
                $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'avatars'
                    . DIRECTORY_SEPARATOR . $user->avatar;
                try {
                    File::delete($filepath);
                } catch (FileNotFoundException $e) {
                    // File sudah dihapus/tidak ada
                }
            }
            // ganti field image dengan image yang baru
            $user->avatar = $filename;
        }

        $user->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Akun dengan nama $user->name berhasil diubah"
        ]);
        
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        if (\Auth::user()->id == $id) {
            Session::flash("flash_notification", [
                "level"=>"warning",
                "message"=>"Tidak dapat menghpaus diri sendiri!"
            ]);

            return redirect()->back();
        }

        if ($user->avatar) {
            $old_image = $user->avatar;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'avatars'
            . DIRECTORY_SEPARATOR . $user->avatar;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        $user->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('user.index');
    }

    public function showProfile()
    {
        $user = \Auth::user();

        return view('users.profile', ['user' => $user]);
    }

    public function updateProfile(Request $request)
    {
        $auth = \Auth::user()->id;
        $user = User::find($auth);
        
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|unique:users,email,' . $auth,
            'identity_number' => 'required|numeric',
            'phone' => 'required|string|max:16'
        ]);

        if ($request->hasFile('avatar')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('avatar');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'avatars';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);
            // hapus image lama, jika ada
            if ($user->avatar) {
                $old_image = $user->avatar;
                if ($user->avatar != 'user-default.jpg') {
                    # delete if not default
                    $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'avatars'
                     . DIRECTORY_SEPARATOR . $user->avatar;
                    try {
                        File::delete($filepath);
                    } catch (FileNotFoundException $e) {
                        // File sudah dihapus/tidak ada
                    }
                }
            }
            // ganti field image dengan image yang baru
            $user->avatar = $filename;
        }
        $user->name = $request->name;
        $user->email = $request->email;
        $user->identity_number = $request->identity_number;
        $user->phone = $request->phone;
        $user->save();
    
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Profil berhasil diubah"
        ]);

        return redirect()->route('profile.show');
    }
}

resources/views/users/create.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Pengguna</h5>
            <span>Kelola data pengguna</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Pengguna</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
    <div class="row">

      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h3>Tambah Pengguna</h3>
          </div>
          <div class="card-body">       
            @csrf

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Nama Lengkap" name="name" value="{{old('name')}}">
                  @error('name')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="identity_number">NIK</label>
                  <input type="text" class="form-control @error('identity_number') is-invalid @enderror" id="identity_number" placeholder="Nomor KTP" name="identity_number" value="{{old('identity_number')}}">
                  @error('identity_number')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="form-group col-7 {{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email">Email</label>
                <input id="email" type="email" class="form-control @if ($errors->has('email')) is-invalid @enderror" name="email" placeholder="Email" value="{{ old('email') }}">
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

              <div class="form-group col-5 {{ $errors->has('phone') ? ' has-error' : '' }}">
                <label for="phone">Nomor Hp</label>
                <input id="phone" type="number" class="form-control @if ($errors->has('phone')) is-invalid @enderror" name="phone" placeholder="Nomor Hp" value="{{ old('phone') }}">
                @error('phone')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

            </div>

            <div class="form-group {{ $errors->has('role') ? ' has-error' : '' }}">
              <label for="role">Hak Akses</label>
              <select name="role" class="form-control select2">
                <option value="admin">Admin</option>
                <option value="technician">Teknisi</option>
                <option value="owner">Owner</option>
              </select>
              @error('role')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>
            
            <div class="row">
              <div class="form-group col-6 {{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="password" class="d-block">Password</label>
                <input id="password" type="password" class="form-control @if ($errors->has('password')) is-invalid @enderror" name="password" placeholder="Minimal 6 Karakter" required>
                @error('password')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
              <div class="form-group col-6">
                <label for="password-confirm" class="d-block">Konfirmasi Password</label>
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" placeholder="Konfirmasi harus sesuai" required>
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-block mr-2">Submit</button>
            
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="card card-primary">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold">Foto Profil</h6>
          </div>
          <div class="card-body">
            <div class="form-group">
              <div class="text-center">
                <img src="{{ asset('assets/tk/img/avatar.jpg') }}" class="rounded-circle" id="avatar-prev" width="200" height="200" alt="avatar">
              </div>
            </div>
            <div class="form-group custom-file mb-3">
              <input id="avatar" type="file" class="custom-file-input {{ $errors->has('avatar') ? ' has-error' : '' }}" name="avatar">
              <label class="custom-file-label" for="customFile">Pilih Gambar</label>
            </div>
            @if ($errors->has('avatar'))
              <div class="invalid-feedback">
                <strong>{{ $errors->first('avatar') }}</strong>
              </div>
            @endif
          </div>
        </div>
      </div>
    </div>
  </form>

</div>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init()
      $('.select2').select2();
    })

    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#avatar-prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]); // convert to base64 string
      }
    }

    $("#avatar").change(function() {
      readURL(this);
    });
  </script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Pengguna</h5>
            <span>Kelola data pengguna</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Pengguna</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <form method="POST" action="{{ route('user.update', $user->id) }}" enctype="multipart/form-data">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h3>Edit Pengguna</h3>
          </div>
          <div class="card-body">
            @csrf
            @method('PUT')

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Nama Lengkap" name="name" value="{{ $user->name }}">
                  @error('name')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="identity_number">NIK</label>
                  <input type="text" class="form-control @error('identity_number') is-invalid @enderror" id="identity_number" placeholder="Nomor KTP" name="identity_number" value="{{ $user->identity_number }}">
                  @error('identity_number')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="form-group col-7 {{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email">Email</label>
                <input id="email" type="email" class="form-control @if ($errors->has('email')) is-invalid @enderror" name="email" placeholder="Email" value="{{ $user->email }}">
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

              <div class="form-group col-5 {{ $errors->has('phone') ? ' has-error' : '' }}">
                <label for="phone">Nomor Hp</label>
                <input id="phone" type="number" class="form-control @if ($errors->has('phone')) is-invalid @enderror" name="phone" placeholder="Nomor Hp" value="{{ $user->phone }}">
                @error('phone')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

            </div>

            <div class="form-group {{ $errors->has('role') ? ' has-error' : '' }}">
              <label for="role">Hak Akses</label>
              <select name="role" class="form-control select2">
                <option value="admin" {{ $user->role=='admin' ? 'selected' : '' }}>Admin</option>
                <option value="technician" {{ $user->role=='technician' ? 'selected' : '' }}>Teknisi</option>
                <option value="owner" {{ $user->role=='owner' ? 'selected' : '' }}>Owner</option>
              </select>
              @error('role')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>
          
            <button type="submit" class="btn btn-primary btn-block mr-2">Submit</button>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="card card-primary">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold">Foto Profil</h6>
          </div>
          <div class="card-body">
            <div class="form-group">
              <div class="text-center">
                @if (is_null($user->avatar))
                  <img src="{{ asset('assets/tk/img/avatar.jpg') }}" class="rounded-circle" id="avatar-prev" width="200" height="200" alt="avatar">
                @else
                  <img alt="image" src="{{asset('uploads/images/avatars/'.$user->avatar)}}" class="rounded-circle" id="avatar-prev" width="200" height="200" alt="avatar">
                @endif
              </div>
            </div>
            <div class="form-group custom-file mb-3">
              <input id="avatar" type="file" class="custom-file-input {{ $errors->has('avatar') ? ' has-error' : '' }}" name="avatar">
              <label class="custom-file-label" for="customFile">Pilih Gambar</label>
            </div>
            @if ($errors->has('avatar'))
              <div class="invalid-feedback">
                <strong>{{ $errors->first('avatar') }}</strong>
              </div>
            @endif
          </div>
        </div>
      </div>

    </div>
  </form>

</div>
@endsection
@section('script')
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init()
      $('.select2').select2();
    })

    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#avatar-prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]); // convert to base64 string
      }
    }

    $("#avatar").change(function() {
      readURL(this);
    });
  </script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Pengguna</h5>
            <span>Kelola data pengguna</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Pengguna</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <a class="btn btn-sm btn-primary mr-2" href="{{ route('user.create') }}"><i class="ik ik-plus"></i> Tambah Data</a>
    <div class="form-inline ml-auto">
      <label for="role">Filter Role</label>
      <select name="role" class="form-control-sm ml-2">
        <option value="all">Semua</option>
        <option value="admin">Admin</option>
        <option value="technician">Teknisi</option>
        <option value="owner">Owner</option>
      </select>
    </div>
  </div>

	<div class="row">
	  <div class="col-md-12">
	    <div class="card">
	      <div class="card-header">
	        <h3>List Pengguna</h3></div>
	      <div class="card-body">
	        <table class="table datatable">
	          <thead>
	            <tr>
	              <th>#</th>
	              <th>Nama</th>
                <th>No. HP</th>
                <th>Email</th>
                <th>Role</th>
	              <th class="text-right">Aksi</th>
	            </tr>
	          </thead>
	          <tbody></tbody>
	        </table>
	      </div>
	    </div>
	  </div>
	</div>

</div>
@endsection

@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          ajax: {
            url: '{{ route('user.index') }}',
            data: function (d) {
              d.role = $('select[name=role]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'phone', name: 'phone', defaultContent: '-'},
            {data: 'email', name: 'email'},
            {data: 'display_role', name: 'display_role', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('select[name=role]').change(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection