routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=>'main', 'middleware'=>['auth']], function () {
    Route::get('user/profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('profile.show');
    Route::put('user/profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('profile.update');

    Route::get('service/{id}/print', [App\Http\Controllers\ServiceController::class, 'print'])->name('service.print');
    Route::get('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupIndex'])->name('service.pickup.index');
    Route::post('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupStore'])->name('service.pickup.store');

    Route::get('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderIndex'])->name('spare_part.order.index');
    Route::post('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderStore'])->name('spare_part.order.store');

    Route::get('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedIndex'])->name('spare_part.received.index');
    Route::post('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedStore'])->name('spare_part.received.store');

    Route::get('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingIndex'])->name('spare_part.fixing.index')->middleware('role:technician');
    Route::post('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingStore'])->name('spare_part.fixing.store')->middleware('role:technician');


    Route::resource('user', App\Http\Controllers\UserController::class)->middleware('role:owner');
    Route::resource('service', App\Http\Controllers\ServiceController::class)->middleware('role:admin');
    Route::resource('customer', App\Http\Controllers\CustomerController::class)->middleware('role:admin');
    Route::resource('symptom', App\Http\Controllers\SymptomController::class)->middleware('role:admin|technician');
    Route::resource('report', App\Http\Controllers\ReportController::class)->middleware('role:admin|owner');
});

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;

    protected $appends = ['display_status', 'display_finish_date', 'display_pickup_date'];

    public function getDisplayStatusAttribute()
    {
        $result = '';
        $status = $this->attributes['status'];

        switch ($status) {
            case '100':
                $result = 'Service Masuk';
                break;

            case '200':
                $result = 'Dalam Proses';
                break;

            case '300':
                $result = 'Menunggu Pengambilan';
                break;

            case '400':
                $result = 'Selesai';
                break;

            case '10':
                $result = 'Batal';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }

    public function getDisplayFinishDateAttribute(){
        return date_std($this->attributes['finish_date']);
    }

    public function getDisplayPickupDateAttribute(){
        return date_std($this->attributes['pickup_date']);
    }

    public function customer()
    {
        return $this->belongsTo('App\Models\Customer', 'customer_id');
    }

    public static function generateCode()
    {
        $date = date('ymd');
        $data = self::whereDate('created_at', $date)->orderBy('id', 'desc')->first();
        $last_code = 'SI'.$date.'00';
        if($data != null){
            $last_code = $data->code;
        }
        $last_increment = substr($last_code, -2);
        
        return 'SI' . $date . str_pad($last_increment + 1, 2, 0, STR_PAD_LEFT);
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Service;
use App\Models\SparePart;
use App\Models\Symptom;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use Session;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $services = Service::with('customer');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $services->whereStatus($request->status);
                }
            }

            $services = $services->select('services.*');
            
            return Datatables::of($services)
                ->addIndexColumn()
                ->addColumn('action', function($service){
                    return view('partials._action', [
                        'model'           => $service,
                        'form_url'        => route('service.destroy', $service->id),
                        'edit_url'        => route('service.edit', $service->id),
                        'show_url'        => route('service.show', $service->id),
                    ]);
                })             
                ->escapeColumns([])
                ->make(true);
        }

        return view('services.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::where('status', 100)->get();

        return view('services.create')->with(compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'date_input' => 'required|date',
            'customer_id' => 'required|integer',
            'item_name' => 'required|string|max:255',
            'item_serial_number' => 'required|string|max:255',
            'is_waranty' => 'required|integer',
            'item_complaint' => 'required|string',
            'item_detail' => 'required|string',
        ]);
        
        $service = new Service();
        $service->code = Service::generateCode();
        $service->date_input = $request->date_input;
        $service->customer_id = $request->customer_id;
        $service->item_name = $request->item_name;
        $service->item_serial_number = $request->item_serial_number;
        $service->is_waranty = $request->is_waranty;
        $service->item_complaint = $request->item_complaint;
        $service->item_detail = $request->item_detail;
        $service->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Service dengan nomor $service->code berhasil dibuat"
        ]);

        Session::flash("do_print", true);
        
        return redirect()->route('service.show', $service->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $service = Service::find($id);

        return view('services.show')->with(compact('service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::find($id);
        $customers = Customer::where('status', 100)->get();

        return view('services.edit')->with(compact('service', 'customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'date_input' => 'required|date',
            'customer_id' => 'required|integer',
            'item_name' => 'required|string|max:255',
            'item_serial_number' => 'required|string|max:255',
            'is_waranty' => 'required|integer',
            'item_complaint' => 'required|string',
            'item_detail' => 'required|string',
        ]);
        
        $service = Service::find($id);
        $service->date_input = $request->date_input;
        $service->customer_id = $request->customer_id;
        $service->item_name = $request->item_name;
        $service->item_serial_number = $request->item_serial_number;
        $service->is_waranty = $request->is_waranty;
        $service->item_complaint = $request->item_complaint;
        $service->item_detail = $request->item_detail;
        $service->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Service dengan nomor $service->code berhasil diubah"
        ]);
        
        return redirect()->route('service.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        
        $symptoms = Symptom::where('service_id', $id)->get();

        foreach ($symptoms as $item) {
            $sp = SparePart::where('symptom_id', $item->id)->first();
            $sp->delete();

            $item->delete();
        }

        $service->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Data Service berhasil dihapus"
        ]);

        return redirect()->back();
    }

    public function print($id)
    {
        $service = Service::find($id);

        return view('services.print')->with(compact('service'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function pickupIndex(Request $request)
    {
        if ($request->ajax()) {

            $services = Service::with('customer')->whereStatus(300);

            $services = $services->select('services.*');
            
            return Datatables::of($services)
                ->addIndexColumn()
                ->addColumn('action', function($service){
                    return view('partials._action_custom', [
                        'model'           => $service,
                        'input_url'       => $service->id,
                    ]);
                })             
                ->escapeColumns([])
                ->make(true);
        }

        return view('services.pickup_index');
    }

    public function pickupStore(Request $request)
    {
        $this->validate($request, [
            'service_id' => 'required|integer',
            'pickup_date' => 'required|date',
        ]);

        $service = Service::find($request->service_id);
        $service->status = 400;
        $service->pickup_date = $request->pickup_date;
        $service->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Service Selesai"
        ]);

        return redirect()->back();
    }
}

resources/views/services/create.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Service</h5>
            <span>Kelola Data Service</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Service</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <form method="POST" action="{{ route('service.store') }}" enctype="multipart/form-data">
    <div class="row">

      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3>Tambah Service</h3>
          </div>
          <div class="card-body">       
            @csrf

            <div class="row">
              <div class="col-md-3">
                <div class="form-group">
                  <label for="date_input">Tanggal Service</label>
                  <input type="date" class="form-control @error('date_input') is-invalid @enderror" id="date_input" placeholder="Tanggal Service" name="date_input" value="{{date('Y-m-d')}}">
                  @error('date_input')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="customer_id">Nama Customer</label>
                  <select name="customer_id" id="customer_id" class="form-control @error('customer_id') is-invalid @enderror">
                    <option value=""></option>
                    @foreach ($customers as $item)
                      <option value="{{ $item->id }}" data-address="{{ $item->address }}">{{ $item->name }}</option>
                    @endforeach
                  </select>
                  @error('customer_id')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              
              <div class="col-md-5">
                <div class="form-group">
                  <label for="customer_address">Alamat</label>
                  <input type="text" class="form-control @error('customer_address') is-invalid @enderror" id="customer_address" placeholder="Alamat" name="customer_address" value="-" readonly>
                  @error('customer_address')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
            </div>

            <hr>

            <div class="row">
              <div class="col-md-5">
                <div class="form-group">
                  <label for="item_name">Nama Barang</label>
                  <input type="text" class="form-control @error('item_name') is-invalid @enderror" id="item_name" placeholder="Nama Barang" name="item_name" value="{{old('item_name')}}">
                  @error('item_name')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-5">
                <div class="form-group">
                  <label for="item_serial_number">SN</label>
                  <input type="text" class="form-control @error('item_serial_number') is-invalid @enderror" id="item_serial_number" placeholder="Serial Number" name="item_serial_number" value="{{old('item_serial_number')}}">
                  @error('item_serial_number')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <div class="form-group">
                    <label for="item_serial_number">Garansi</label>
                    <div>
                      <input type="checkbox" id="switch_waranty" name="switch_waranty" class="js-single" checked />
                      <input type="hidden" name="is_waranty" id="is_waranty" value="1">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="form-group col-6 {{ $errors->has('item_complaint') ? ' has-error' : '' }}">
                <label for="item_complaint">Keluhan</label>
                <textarea name="item_complaint" id="item_complaint" class="form-control @if ($errors->has('item_complaint')) is-invalid @enderror" rows="5" placeholder="Keluhan">{{ old('item_complaint') }}</textarea>
                @error('item_complaint')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
              <div class="form-group col-6 {{ $errors->has('item_detail') ? ' has-error' : '' }}">
                <label for="item_detail">Kelengkapan</label>
                <textarea name="item_detail" id="item_detail" class="form-control @if ($errors->has('item_detail')) is-invalid @enderror" rows="5" placeholder="Kelengkapan">{{ old('item_detail') }}</textarea>
                @error('item_detail')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div>

           
            <button type="submit" class="btn btn-primary btn-block mr-2">Submit</button>
            
          </div>
        </div>
      </div>

    </div>
  </form>

</div>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      $('#customer_id').select2({
        placeholder: "Pilih atau Cari Customer",
      });

      // Single swithces
      var elemsingle = document.querySelector('.js-single');
      var switchery = new Switchery(elemsingle, {
          color: '#4099ff',
          jackColor: '#fff'
      });
    })

    $('#customer_id').on('change', function(){
      var address = $(this).find('option:selected').attr('data-address');
      $("#customer_address").val(address);
    })

    $('#switch_waranty').on('change', function(){
      var check = $(this).is(':checked')
      $("#is_waranty").val((check == true ? 1 : 0));
    })
  </script>
@endsection

resources/views/services/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Service</h5>
            <span>Kelola Data Service</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Service</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <form method="POST" action="{{ route('service.update', $service->id) }}" enctype="multipart/form-data">
    <div class="row">

      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3>Edit Service</h3>
          </div>
          <div class="card-body">       
            @csrf
            @method('PUT')

            <div class="row">
              <div class="col-md-3">
                <div class="form-group">
                  <label for="date_input">Tanggal Service</label>
                  <input type="date" class="form-control @error('date_input') is-invalid @enderror" id="date_input" placeholder="Tanggal Service" name="date_input" value="{{$service->date_input}}">
                  @error('date_input')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="customer_id">Nama Customer</label>
                  <select name="customer_id" id="customer_id" class="form-control @error('customer_id') is-invalid @enderror">
                    <option value=""></option>
                    @foreach ($customers as $item)
                      <option value="{{ $item->id }}" data-address="{{ $item->address }}" {{ $item->id == $service->customer_id ? 'selected' : '' }}>{{ $item->name }}</option>
                    @endforeach
                  </select>
                  @error('customer_id')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              
              <div class="col-md-5">
                <div class="form-group">
                  <label for="customer_address">Alamat</label>
                  <input type="text" class="form-control @error('customer_address') is-invalid @enderror" id="customer_address" placeholder="Alamat" name="customer_address" value="-" readonly>
                  @error('customer_address')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
            </div>

            <hr>

            <div class="row">
              <div class="col-md-5">
                <div class="form-group">
                  <label for="item_name">Nama Barang</label>
                  <input type="text" class="form-control @error('item_name') is-invalid @enderror" id="item_name" placeholder="Nama Barang" name="item_name" value="{{$service->item_name}}">
                  @error('item_name')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-5">
                <div class="form-group">
                  <label for="item_serial_number">SN</label>
                  <input type="text" class="form-control @error('item_serial_number') is-invalid @enderror" id="item_serial_number" placeholder="Serial Number" name="item_serial_number" value="{{$service->item_serial_number}}">
                  @error('item_serial_number')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <div class="form-group">
                    <label for="item_serial_number">Garansi</label>
                    <div>
                      <input type="checkbox" id="switch_waranty" name="switch_waranty" class="js-single" {{ $service->is_waranty == 1 ? 'checked' : '' }} />
                      <input type="hidden" name="is_waranty" id="is_waranty" value="{{ $service->is_waranty == 1 ? '1' : '0' }}">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="form-group col-6 {{ $errors->has('item_complaint') ? ' has-error' : '' }}">
                <label for="item_complaint">Keluhan</label>
                <textarea name="item_complaint" id="item_complaint" class="form-control @if ($errors->has('item_complaint')) is-invalid @enderror" rows="5" placeholder="Keluhan">{{ $service->item_complaint }}</textarea>
                @error('item_complaint')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
              <div class="form-group col-6 {{ $errors->has('item_detail') ? ' has-error' : '' }}">
                <label for="item_detail">Kelengkapan</label>
                <textarea name="item_detail" id="item_detail" class="form-control @if ($errors->has('item_detail')) is-invalid @enderror" rows="5" placeholder="Kelengkapan">{{ $service->item_detail }}</textarea>
                @error('item_detail')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div>

           
            <button type="submit" class="btn btn-primary btn-block mr-2">Submit</button>
            
          </div>
        </div>
      </div>

    </div>
  </form>

</div>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      $('#customer_id').select2({
        placeholder: "Pilih atau Cari Customer",
      });

      // Single swithces
      var elemsingle = document.querySelector('.js-single');
      var switchery = new Switchery(elemsingle, {
          color: '#4099ff',
          jackColor: '#fff'
      });

      $('#customer_id').change();
    })

    $('#customer_id').on('change', function(){
      var address = $(this).find('option:selected').attr('data-address');
      $("#customer_address").val(address);
    })

    $('#switch_waranty').on('change', function(){
      var check = $(this).is(':checked')
      $("#is_waranty").val((check == true ? 1 : 0));
    })
  </script>
@endsection

resources/views/services/index.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Service</h5>
            <span>Kelola data Service</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Service</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <a class="btn btn-sm btn-primary mr-2" href="{{ route('service.create') }}"><i class="ik ik-plus"></i> Tambah Data</a>
    <div class="form-inline ml-auto">
      <label for="status">Filter Status</label>
      <select name="status" class="form-control-sm ml-2">
        <option value="all">Semua</option>
        <option value="100">Service Masuk</option>
        <option value="200">Dalam Proses</option>
        <option value="300">Menunggu Diambil</option>
        <option value="400">Selesai</option>
        <option value="10">Batal</option>
      </select>
    </div>
  </div>

	<div class="row">
	  <div class="col-md-12">
	    <div class="card">
	      <div class="card-header">
	        <h3>List Service</h3></div>
	      <div class="card-body">
	        <table class="table datatable">
	          <thead>
	            <tr>
	              <th>#</th>
	              <th>Kode Service</th>
	              <th>Nama Barang</th>
                <th>SN</th>
                <th>Customer</th>
                <th>Status</th>
	              <th class="text-right">Aksi</th>
	            </tr>
	          </thead>
	          <tbody></tbody>
	        </table>
	      </div>
	    </div>
	  </div>
	</div>

</div>
@endsection

@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          ajax: {
            url: '{{ route('service.index') }}',
            data: function (d) {
              d.status = $('select[name=status]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'item_name', name: 'item_name'},
            {data: 'item_serial_number', name: 'item_serial_number'},
            {data: 'customer.name', name: 'customer.name', defaultContent: '-'},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('select[name=status]').change(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection