routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=>'main', 'middleware'=>['auth']], function () {
    Route::get('user/profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('profile.show');
    Route::put('user/profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('profile.update');

    Route::get('service/{id}/print', [App\Http\Controllers\ServiceController::class, 'print'])->name('service.print');
    Route::get('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupIndex'])->name('service.pickup.index');
    Route::post('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupStore'])->name('service.pickup.store');

    Route::get('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderIndex'])->name('spare_part.order.index');
    Route::post('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderStore'])->name('spare_part.order.store');

    Route::get('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedIndex'])->name('spare_part.received.index');
    Route::post('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedStore'])->name('spare_part.received.store');

    Route::get('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingIndex'])->name('spare_part.fixing.index')->middleware('role:technician');
    Route::post('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingStore'])->name('spare_part.fixing.store')->middleware('role:technician');


    Route::resource('user', App\Http\Controllers\UserController::class)->middleware('role:owner');
    Route::resource('service', App\Http\Controllers\ServiceController::class)->middleware('role:admin');
    Route::resource('customer', App\Http\Controllers\CustomerController::class)->middleware('role:admin');
    Route::resource('symptom', App\Http\Controllers\SymptomController::class)->middleware('role:admin|technician');
    Route::resource('report', App\Http\Controllers\ReportController::class)->middleware('role:admin|owner');
});

app/Models/Symptom.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Symptom extends Model
{
    use HasFactory;
    protected $appends = ['display_status', 'display_date'];

    public function getDisplayStatusAttribute()
    {
        $result = '';
        $status = $this->attributes['status'];

        switch ($status) {
            case '100':
                $result = 'Waiting Order';
                break;

            case '200':
                $result = 'Waiting Part';
                break;

            case '300':
                $result = 'Waiting Repair';
                break;

            case '400':
                $result = 'Finish';
                break;

            case '10':
                $result = 'Batal';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }

    public function getDisplayDateAttribute(){
        return date_std($this->attributes['created_at']);
    }

    public function service()
    {
        return $this->belongsTo('App\Models\Service', 'service_id');
    }

    public function technician()
    {
        return $this->belongsTo('App\Models\User', 'technician_id');
    }

    public function sparePart()
    {
        return $this->hasOne('App\Models\SparePart', 'symptom_id');
    }
}

app/Http/Controllers/SymptomController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Service;
use App\Models\Symptom;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use Session;

class SymptomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $services = Service::with('customer');
            $services->whereBetween('status', [100, 200]);
            $services = $services->select('services.*');
            
            return Datatables::of($services)
                ->addIndexColumn()
                ->addColumn('action', function($service){
                    return view('partials._action', [
                        'model'           => $service,
                        'input_url'        => route('symptom.show', $service->id),
                    ]);
                })             
                ->escapeColumns([])
                ->make(true);
        }

        return view('symptoms.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'service_id' => 'required|integer',
            'sn_part' => 'required|string|max:255',
            'pd_code' => 'required|string|max:255',
            'symptom' => 'required|string',
            'root_cause' => 'required|string',
            'resolution' => 'required|string',
        ]);

        $status_service = 200;
        $status_symp = 100;
        if ($request->is_no_replacing_new_part == 1){
            $status_service = 300; // finish
            $status_symp = 400; // finish
        }
        
        $symptom = new Symptom;
        $symptom->service_id = $request->service_id;
        $symptom->technician_id = auth()->user()->id;
        $symptom->sn_part = $request->sn_part;
        $symptom->pd_code = $request->pd_code;
        $symptom->symptom = $request->symptom;
        $symptom->root_cause = $request->root_cause;
        $symptom->resolution = $request->resolution;
        $symptom->status = $status_symp;
        $symptom->save();

        $service = Service::find($request->service_id);
        $service->status = $status_service;
        $service->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Symptom berhasil dibuat"
        ]);
        
        return redirect()->route('symptom.show', $request->service_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $service = Service::find($id);
        $symptoms = Symptom::where('service_id', $id)->get();

        return view('symptoms.create')->with(compact('symptoms', 'service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function detail($id)
    {
        $status = 0;
        $symptom = Symptom::with('service', 'service.customer', 'sparePart')->where('id', $id)->first();

        if ($symptom != null){
            $status = 1;
        }

        $data = [
            'status' => $status,
            'data' => $symptom
        ];

        return response()->json($data);
    }
}

resources/views/symptoms/create.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Symptom</h5>
            <span>Kelola data Symptom</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Symptom</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

	<div class="row">
	  <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex">
          <h3>Detail Service</h3>          
        </div>
        <div class="card-body">       
          @csrf
          @method('PUT')

          <div class="row">
            <div class="col-md-3">
              <div class="form-group">
                <label for="date_input">Tanggal Service</label>
                <input type="date" class="form-control" placeholder="Tanggal Service" name="date_input" value="{{$service->date_input}}" readonly>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="customer_id">Nama Customer</label>
                <input type="text" class="form-control" value="{{ $service->customer->name }}" readonly>
              </div>
            </div>
            
            <div class="col-md-5">
              <div class="form-group">
                <label for="customer_address">Alamat</label>
                <input type="text" class="form-control" id="customer_address" placeholder="Alamat" name="customer_address" value="{{ $service->customer->address }}" readonly>
              </div>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-5">
              <div class="form-group">
                <label for="item_name">Nama Barang</label>
                <input type="text" class="form-control" id="item_name" placeholder="Nama Barang" name="item_name" value="{{$service->item_name}}" readonly>
              </div>
            </div>
            <div class="col-md-5">
              <div class="form-group">
                <label for="item_serial_number">SN</label>
                <input type="text" class="form-control" id="item_serial_number" placeholder="Serial Number" name="item_serial_number" value="{{$service->item_serial_number}}" readonly>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2">
                <div class="form-group">
                  <label for="item_serial_number">Garansi</label>
                  <div>
                    <input type="checkbox" id="switch_waranty" name="switch_waranty" class="js-single" {{ $service->is_waranty == 1 ? 'checked' : '' }} disabled />
                    <input type="hidden" name="is_waranty" id="is_waranty" value="{{ $service->is_waranty == 1 ? '1' : '0' }}">
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="row">
            <div class="form-group col-6">
              <label for="item_complaint">Keluhan</label>
              <textarea name="item_complaint" id="item_complaint" class="form-control" rows="5" placeholder="Keluhan" readonly>{{ $service->item_complaint }}</textarea>
            </div>
            <div class="form-group col-6">
              <label for="item_detail">Kelengkapan</label>
              <textarea name="item_detail" id="item_detail" class="form-control" rows="5" placeholder="Kelengkapan" readonly>{{ $service->item_detail }}</textarea>
            </div>
          </div>
          
        </div>
      </div>

	    <div class="card">
	      <div class="card-header d-flex">
	        <h3>List Symptom</h3>
          <button type="button" class="btn btn-primary ml-auto" data-toggle="modal" data-target=".modal-add-symp"><i class="ik ik-plus"></i> Tambah</button>
        </div>
	      <div class="card-body">
	        <table class="table datatable">
	          <thead>
	            <tr>
	              <th>#</th>
	              <th>Tanggal Symptom</th>
	              <th>Teknisi</th>
                <th>PD Code</th>
                <th>Customer</th>
	            </tr>
	          </thead>
	          <tbody>
              @foreach ($symptoms as $index => $item)
                <tr>
                  <td>{{ ++$index }}</td>
                  <td>{{ date_std($item->created_at) }}</td>
                  <td>{{ $item->technician->name }}</td>
                  <td>{{ $item->pd_code }}</td>
                  <td>{{ $item->service->customer->name }}</td>
                </tr>
              @endforeach
            </tbody>
	        </table>
	      </div>
	    </div>
	  </div>
	</div>

</div>

<div class="modal fade modal-add-symp" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <form method="POST" action="{{ route('symptom.store') }}" enctype="multipart/form-data">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Tambah Symptom</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          @csrf

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="no_replacing_new_part">No Replacing New Part</label>
                <div>
                  <input type="checkbox" id="switch_no_replacing_new_part" name="switch_no_replacing_new_part" class="js-single2" />
                  <input type="hidden" name="is_no_replacing_new_part" id="is_no_replacing_new_part" value="0">
                  <input type="hidden" name="service_id"  value="{{ $service->id }}">
                </div>
              </div>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="sn_part">SN Part</label>
                <input type="text" class="form-control @error('sn_part') is-invalid @enderror" id="sn_part" placeholder="Serial Number" name="sn_part" value="{{old('sn_part')}}">
                @error('sn_part')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="pd_code">PD Code</label>
                <input type="text" class="form-control @error('pd_code') is-invalid @enderror" id="pd_code" placeholder="PD Code" name="pd_code" value="{{old('pd_code')}}">
                @error('item_name')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group col-12 {{ $errors->has('symptom') ? ' has-error' : '' }}">
              <label for="symptom">Symptom</label>
              <textarea name="symptom" id="symptom" class="form-control @if ($errors->has('symptom')) is-invalid @enderror" rows="3" placeholder="Symptom">{{ old('symptom') }}</textarea>
              @error('symptom')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>
          </div>
          
          <div class="row">
            <div class="form-group col-6 {{ $errors->has('root_cause') ? ' has-error' : '' }}">
              <label for="root_cause">Root Cause</label>
              <textarea name="root_cause" id="root_cause" class="form-control @if ($errors->has('root_cause')) is-invalid @enderror" rows="3" placeholder="Root Cause">{{ old('root_cause') }}</textarea>
              @error('root_cause')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>
            <div class="form-group col-6 {{ $errors->has('resolution') ? ' has-error' : '' }}">
              <label for="resolution">Resolution</label>
              <textarea name="resolution" id="resolution" class="form-control @if ($errors->has('resolution')) is-invalid @enderror" rows="3" placeholder="Resolution">{{ old('resolution') }}</textarea>
              @error('resolution')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Simpan</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection



@section('script')
<script>
  $(document).ready(function() {
    @if ($errors->isNotEmpty())
      $('.modal-add-symp').modal('show');
    @endif
    
    // Single swithces
    var elemsingle = document.querySelector('.js-single');
    var switchery = new Switchery(elemsingle, {
        color: '#4099ff',
        jackColor: '#fff'
    });

    // Single swithces
    var elemsingle = document.querySelector('.js-single2');
    var switchery = new Switchery(elemsingle, {
        color: '#4099ff',
        jackColor: '#fff'
    });
  });

  $('#switch_no_replacing_new_part').on('change', function(){
    var check = $(this).is(':checked')
    $("#is_no_replacing_new_part").val((check == true ? 1 : 0));
  })
</script>
@endsection

resources/views/symptoms/index.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Symptom</h5>
            <span>Kelola data Symptom</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Symptom</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  {{-- <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <a class="btn btn-sm btn-primary mr-2" href="{{ route('service.create') }}"><i class="ik ik-plus"></i> Tambah Data</a>
    <div class="form-inline ml-auto">
      <label for="status">Filter Status</label>
      <select name="status" class="form-control-sm ml-2">
        <option value="all">Semua</option>
        <option value="100">Aktif</option>
        <option value="10">Tidak Aktif</option>
      </select>
    </div>
  </div> --}}

	<div class="row">
	  <div class="col-md-12">
	    <div class="card">
	      <div class="card-header">
	        <h3>List Service</h3></div>
	      <div class="card-body">
	        <table class="table datatable">
	          <thead>
	            <tr>
	              <th>#</th>
	              <th>Kode Service</th>
	              <th>Nama Barang</th>
                <th>SN</th>
                <th>Customer</th>
                <th>Status</th>
	              <th class="text-right">Aksi</th>
	            </tr>
	          </thead>
	          <tbody></tbody>
	        </table>
	      </div>
	    </div>
	  </div>
	</div>

</div>
@endsection

@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          ajax: {
            url: '{{ route('symptom.index') }}',
            data: function (d) {
              d.status = $('select[name=status]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'item_name', name: 'item_name'},
            {data: 'item_serial_number', name: 'item_serial_number'},
            {data: 'customer.name', name: 'customer.name', defaultContent: '-'},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('select[name=status]').change(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection