routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=>'main', 'middleware'=>['auth']], function () {
    Route::get('user/profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('profile.show');
    Route::put('user/profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('profile.update');

    Route::get('service/{id}/print', [App\Http\Controllers\ServiceController::class, 'print'])->name('service.print');
    Route::get('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupIndex'])->name('service.pickup.index');
    Route::post('service/pickup', [App\Http\Controllers\ServiceController::class, 'pickupStore'])->name('service.pickup.store');

    Route::get('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderIndex'])->name('spare_part.order.index');
    Route::post('spare_part/order', [App\Http\Controllers\SparePartController::class, 'orderStore'])->name('spare_part.order.store');

    Route::get('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedIndex'])->name('spare_part.received.index');
    Route::post('spare_part/received', [App\Http\Controllers\SparePartController::class, 'receivedStore'])->name('spare_part.received.store');

    Route::get('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingIndex'])->name('spare_part.fixing.index')->middleware('role:technician');
    Route::post('spare_part/fixing', [App\Http\Controllers\SparePartController::class, 'fixingStore'])->name('spare_part.fixing.store')->middleware('role:technician');


    Route::resource('user', App\Http\Controllers\UserController::class)->middleware('role:owner');
    Route::resource('service', App\Http\Controllers\ServiceController::class)->middleware('role:admin');
    Route::resource('customer', App\Http\Controllers\CustomerController::class)->middleware('role:admin');
    Route::resource('symptom', App\Http\Controllers\SymptomController::class)->middleware('role:admin|technician');
    Route::resource('report', App\Http\Controllers\ReportController::class)->middleware('role:admin|owner');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Self_;

class Customer extends Model
{
    use HasFactory;

    protected $appends = ['display_status'];

    public function getDisplayStatusAttribute()
    {
        $result = '';
        $status = $this->attributes['status'];

        switch ($status) {
            case '100':
                $result = 'Aktif';
                break;

            case '10':
                $result = 'Tidak Aktif';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }

    public static function generateCode()
    {
        $data = self::orderBy('id', 'desc')->first();
        $last_code = 'PEL0000000';
        if($data != null){
            $last_code = $data->code;
        }
        $last_increment = substr($last_code, -7);
        
        return 'PEL' . str_pad($last_increment + 1, 7, 0, STR_PAD_LEFT);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Models\Customer;
use App\Models\Service;
use Session;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $customers = Customer::query();

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $customers->whereStatus($request->status);
                }
            }

            $customers = $customers->select('customers.*');
            
            return Datatables::of($customers)
                ->addIndexColumn()
                ->addColumn('action', function($customer){
                    return view('partials._action', [
                        'model'           => $customer,
                        'form_url'        => route('customer.destroy', $customer->id),
                        'edit_url'        => route('customer.edit', $customer->id),
                        'show_url'        => route('customer.show', $customer->id),
                    ]);
                })             
                ->escapeColumns([])
                ->make(true);
        }

        return view('customers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            //'birth_date' => 'date',
            //'identity_number' => 'required|numeric|digits:16',
            'address' => 'required|string',
            'city' => 'required|string',
            'phone' => 'required|string|max:16',
            'email' => 'required|string|max:255',
            //'fax' => 'required|string',
            //'npwp' => 'required|string|max:16',
        ]);
        
        $customer = new Customer();
        $customer->code = Customer::generateCode();
        $customer->name = $request->name;
        $customer->birth_date = $request->birth_date;
        $customer->identity_number = $request->identity_number;
        $customer->address = $request->address;
        $customer->city = $request->city;
        $customer->phone = $request->phone;
        $customer->email = $request->email;
        $customer->fax = $request->fax;
        $customer->npwp = $request->npwp;
        $customer->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Customer dengan nama $customer->name berhasil dibuat"
        ]);
        
        return redirect()->route('customer.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customer = Customer::find($id);

        return view('customers.show')->with(compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::find($id);

        return view('customers.edit')->with(compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            //'birth_date' => 'date',
            //'identity_number' => 'required|numeric|digits:16',
            'address' => 'required|string',
            'city' => 'required|string',
            'phone' => 'required|string|max:16',
            'email' => 'required|string|max:255',
            //'fax' => 'required|string',
            //'npwp' => 'required|string|max:16',
            'status' => 'required|numeric',
        ]);
        
        $customer = Customer::find($id);
        $customer->name = $request->name;
        $customer->birth_date = $request->birth_date;
        $customer->identity_number = $request->identity_number;
        $customer->address = $request->address;
        $customer->city = $request->city;
        $customer->phone = $request->phone;
        $customer->email = $request->email;
        $customer->fax = $request->fax;
        $customer->npwp = $request->npwp;
        $customer->status = $request->status;
        $customer->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Customer dengan nama $customer->name berhasil diubah"
        ]);
        
        return redirect()->route('customer.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::find($id);

        // cek apakah memeiliki data service
        $check = Service::where('customer_id', $customer)->count();
        if ($check > 0){
            Session::flash("flash_notification", [
                "level"=>"warning",
                "message"=>"Tidak bisa menghapus customer, karena customer memiliki data service, alternatif dapat diubah status menjadi nonaktif!"
            ]);

            return redirect()->back();
        }

        $customer->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Customer berhasil dihapus"
        ]);

        return redirect()->back();
    }
}

resources/views/customers/create.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Customer</h5>
            <span>Kelola Data Customer</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Customer</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <form method="POST" action="{{ route('customer.store') }}" enctype="multipart/form-data">
    <div class="row">

      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3>Tambah Customer</h3>
          </div>
          <div class="card-body">       
            @csrf

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Nama Lengkap" name="name" value="{{old('name')}}">
                  @error('name')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              {{-- <div class="col-md-4">
                <div class="form-group">
                  <label for="birth_date">Tanggal Lahir</label>
                  <input type="date" class="form-control @error('birth_date') is-invalid @enderror" id="birth_date" placeholder="Nomor KTP" name="birth_date" value="{{old('birth_date')}}">
                  @error('birth_date')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div> --}}
              
            </div>

            <div class="row">
              <div class="col-md-8">
                <div class="form-group">
                  <label for="address">Alamat</label>
                  <input type="text" class="form-control @error('address') is-invalid @enderror" id="address" placeholder="Alamat" name="address" value="{{old('address')}}">
                  @error('address')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="city">Kota</label>
                  <input type="text" class="form-control @error('city') is-invalid @enderror" id="city" placeholder="Kota" name="city" value="{{old('city')}}">
                  @error('city')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="form-group col-5 {{ $errors->has('phone') ? ' has-error' : '' }}">
                <label for="phone">Nomor Hp</label>
                <input id="phone" type="number" class="form-control @if ($errors->has('phone')) is-invalid @enderror" name="phone" placeholder="Nomor Hp" value="{{ old('phone') }}">
                @error('phone')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

              <div class="form-group col-7 {{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email">Email</label>
                <input id="email" type="email" class="form-control @if ($errors->has('email')) is-invalid @enderror" name="email" placeholder="Email" value="{{ old('email') }}">
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div>

            {{-- <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="identity_number">NIK</label>
                  <input type="text" class="form-control @error('identity_number') is-invalid @enderror" id="identity_number" placeholder="Nomor KTP" name="identity_number" value="{{old('identity_number')}}">
                  @error('identity_number')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              
              <div class="form-group col-4 {{ $errors->has('fax') ? ' has-error' : '' }}">
                <label for="fax">Fax</label>
                <input id="fax" type="number" class="form-control @if ($errors->has('fax')) is-invalid @enderror" name="fax" placeholder="Fax" value="{{ old('fax') }}">
                @error('fax')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

              <div class="form-group col-4 {{ $errors->has('npwp') ? ' has-error' : '' }}">
                <label for="npwp">NPWP</label>
                <input id="npwp" type="number" class="form-control @if ($errors->has('npwp')) is-invalid @enderror" name="npwp" placeholder="Email" value="{{ old('npwp') }}">
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div> --}}

           
            <button type="submit" class="btn btn-primary btn-block mr-2">Submit</button>
            
          </div>
        </div>
      </div>

    </div>
  </form>

</div>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      $('.select2').select2();
    })
  </script>
@endsection

resources/views/customers/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Customer</h5>
            <span>Kelola Data Customer</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Customer</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <form method="POST" action="{{ route('customer.update', $customer->id) }}" enctype="multipart/form-data">
    <div class="row">

      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3>Edit Customer</h3>
          </div>
          <div class="card-body">       
            @csrf
            @method('PUT')

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Nama Lengkap" name="name" value="{{ $customer->name }}">
                  @error('name')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              {{-- <div class="col-md-3">
                <div class="form-group">
                  <label for="birth_date">Tanggal Lahir</label>
                  <input type="date" class="form-control @error('birth_date') is-invalid @enderror" id="birth_date" placeholder="Nomor KTP" name="birth_date" value="{{$customer->birth_date}}">
                  @error('birth_date')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div> --}}
              
            </div>

            <div class="row">
              <div class="col-md-8">
                <div class="form-group">
                  <label for="address">Alamat</label>
                  <input type="text" class="form-control @error('address') is-invalid @enderror" id="address" placeholder="Alamat" name="address" value="{{$customer->address}}">
                  @error('address')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="city">Kota</label>
                  <input type="text" class="form-control @error('city') is-invalid @enderror" id="city" placeholder="Kota" name="city" value="{{$customer->city}}">
                  @error('city')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="form-group col-5 {{ $errors->has('phone') ? ' has-error' : '' }}">
                <label for="phone">Nomor Hp</label>
                <input id="phone" type="number" class="form-control @if ($errors->has('phone')) is-invalid @enderror" name="phone" placeholder="Nomor Hp" value="{{ $customer->phone }}">
                @error('phone')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

              <div class="form-group col-7 {{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email">Email</label>
                <input id="email" type="email" class="form-control @if ($errors->has('email')) is-invalid @enderror" name="email" placeholder="Email" value="{{ $customer->email}}">
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div>

            {{-- <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="identity_number">NIK</label>
                  <input type="text" class="form-control @error('identity_number') is-invalid @enderror" id="identity_number" placeholder="Nomor KTP" name="identity_number" value="{{$customer->identity_number}}">
                  @error('identity_number')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>

              <div class="form-group col-4 {{ $errors->has('fax') ? ' has-error' : '' }}">
                <label for="fax">Fax</label>
                <input id="fax" type="number" class="form-control @if ($errors->has('fax')) is-invalid @enderror" name="fax" placeholder="Fax" value="{{ $customer->fax}}">
                @error('fax')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>

              <div class="form-group col-4 {{ $errors->has('npwp') ? ' has-error' : '' }}">
                <label for="npwp">NPWP</label>
                <input id="npwp" type="number" class="form-control @if ($errors->has('npwp')) is-invalid @enderror" name="npwp" placeholder="Email" value="{{ $customer->npwp }}">
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div> --}}

            <div class="row">
              <div class="form-group col-4 {{ $errors->has('status') ? ' has-error' : '' }}">
                <label for="status">Status</label>
                <select name="status" class="form-control select2">
                  <option value="100" {{ $customer->status=='100' ? 'selected' : '' }}>Aktif</option>
                  <option value="10" {{ $customer->status=='10' ? 'selected' : '' }}>Tidak Aktif</option>
                </select>
                @error('email')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div>

           
            <button type="submit" class="btn btn-primary btn-block mr-2">Submit</button>
            
          </div>
        </div>
      </div>

    </div>
  </form>

</div>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      $('.select2').select2();
    })
  </script>
@endsection

resources/views/customers/index.blade.php
@extends('layouts.main')

@section('content')
<div class="container-fluid"> 

	<div class="page-header">
    <div class="row align-items-end">
      <div class="col-lg-8">
        <div class="page-header-title">
          <i class="ik ik-bookmark bg-blue"></i>
          <div class="d-inline">
            <h5>Customer</h5>
            <span>Kelola data Customer</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{ route('home') }}"><i class="ik ik-home"></i></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Customer</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <a class="btn btn-sm btn-primary mr-2" href="{{ route('customer.create') }}"><i class="ik ik-plus"></i> Tambah Data</a>
    <div class="form-inline ml-auto">
      <label for="status">Filter Status</label>
      <select name="status" class="form-control-sm ml-2">
        <option value="all">Semua</option>
        <option value="100">Aktif</option>
        <option value="10">Tidak Aktif</option>
      </select>
    </div>
  </div>

	<div class="row">
	  <div class="col-md-12">
	    <div class="card">
	      <div class="card-header">
	        <h3>List Customer</h3></div>
	      <div class="card-body">
	        <table class="table datatable">
	          <thead>
	            <tr>
	              <th>#</th>
	              <th>Kode</th>
	              <th>Nama</th>
                <th>Alamat</th>
                <th>No Hp</th>
                <th>Status</th>
	              <th class="text-right">Aksi</th>
	            </tr>
	          </thead>
	          <tbody></tbody>
	        </table>
	      </div>
	    </div>
	  </div>
	</div>

</div>
@endsection

@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          ajax: {
            url: '{{ route('customer.index') }}',
            data: function (d) {
              d.status = $('select[name=status]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'name', name: 'name'},
            {data: 'address', name: 'address', defaultContent: '-'},
            {data: 'phone', name: 'phone'},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('select[name=status]').change(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection